(defun jpn-recipe ()

  (interactive)
  (beginning-of-buffer)
  (replace-string " (see this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string " (see this page)" "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(see this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(see this page)" "（見此頁）")
  (beginning-of-buffer)
  (replace-string " (this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string " (this page)" "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(this page)" "（見此頁）")
  
  (beginning-of-buffer)
  (replace-string " Tbsps " "湯匙 ")
  (beginning-of-buffer)
  (replace-string " Tbsp " "湯匙 ")
  (beginning-of-buffer)
  (replace-string " tsps " "茶匙 ")
  (beginning-of-buffer)
  (replace-string " tsp " "茶匙 ")
  (beginning-of-buffer)
  (replace-string " cups " "杯 ")
  (beginning-of-buffer)
  (replace-string " cup " "杯 ")
  (beginning-of-buffer)
  (replace-string " dark soy sauce\n" " 濃口醬油\n")
  (beginning-of-buffer)
  (replace-string " light soy sauce\n" " 薄口醬油\n")
  (beginning-of-buffer)
  (replace-string " mirin\n" " 味醂\n")
  (beginning-of-buffer)
  (replace-string " dashi\n" " 出汁\n")
  (beginning-of-buffer)
  (replace-string " small onion\n" "隻 小洋蔥")
  (beginning-of-buffer)
  (replace-string " eggs, beaten\n" "隻 雞蛋（打散）\n")
  (beginning-of-buffer)
  (replace-string " eggs yolks, beaten\n" "隻 蛋黃（打散）\n")

  (beginning-of-buffer)
  (replace-string " large shrimp\n" "4隻 蝦（大）\n")
  (beginning-of-buffer)
  (replace-string " medium shrimp\n" "隻 蝦（中）\n")
  (beginning-of-buffer)
  (replace-string " eggs yolks, beaten\n" "隻 蛋黃（打散）\n")
  (beginning-of-buffer)
  (replace-string " eggs yolks, beaten\n" "隻 蛋黃（打散）\n")
  (beginning-of-buffer)
  (replace-string " eggs yolks, beaten\n" "隻 蛋黃（打散）\n")
  


  (beginning-of-buffer)
  (replace-string " sifted flour\n" " 麵粉（過篩）\n")
  (beginning-of-buffer)
  (replace-string " flour\n" " 麵粉\n")
  (beginning-of-buffer)
  (replace-string " sugar\n" " 砂糖\n")
  (beginning-of-buffer)
  (replace-string " cold water\n" " 冷水\n")
  (beginning-of-buffer)
  (replace-string " ice water\n" " 冰水\n")
  (beginning-of-buffer)
  (replace-string " water\n" " 水\n")
  (beginning-of-buffer)
  (replace-string " saké\n" " 清酒\n")
  (beginning-of-buffer)
  (replace-string " servings\n" "人份\n")
  (beginning-of-buffer)
  (replace-string "1 serving\n" "1人份\n")
  (beginning-of-buffer)
  (replace-string " fresh ginger juice\n" " 新鮮薑汁\n")
  (beginning-of-buffer)
  (replace-string " salt\n" " 鹽\n")
  (beginning-of-buffer)
  (replace-string " eggs\n" "隻 雞蛋\n")
  (beginning-of-buffer)

  (beginning-of-buffer)
  (replace-string " tamari sauce\n" " 溜醬油\n")
  (beginning-of-buffer)
  (replace-string " square giant kelp (konbu)\n" " 昆布\n")
  (beginning-of-buffer)
  (replace-string " giant kelp (konbu)\n" " 昆布\n")
  (beginning-of-buffer)
  (replace-string " dried bonito flakes (hana-katsuo)\n" " 木魚花\n")
  (beginning-of-buffer)
  (replace-string " mirin, alcohol burned off\n" " 味醂（燒去酒精）\n")
  (beginning-of-buffer)
  (replace-string " white miso\n" " 白味噌\n")
  (beginning-of-buffer)
  (replace-string " red miso\n" " 赤味噌\n")
  (beginning-of-buffer)
  (replace-string " rice vinegar\n" " 米醋\n")
  (beginning-of-buffer)
  (replace-string " egg yolks\n" "隻 蛋黃\n")
  (beginning-of-buffer)
  (replace-string " egg yolk\n" "隻 蛋黃\n")
  (beginning-of-buffer)
  (replace-string " egg whites\n" "隻 蛋白\n")
  (beginning-of-buffer)
  (replace-string " egg white\n" "隻 蛋白\n")

  (beginning-of-buffer)
  (replace-string "fresh ginger juice" "新鮮薑汁")
  (beginning-of-buffer)
  (replace-string "finely grated fresh ginger" "現磨薑茸")


  (beginning-of-buffer)
  (replace-string "\nsalt\n\n" "\n鹽\n\n")
  (beginning-of-buffer)
  (replace-string "\nsaké\n\n" "\n清酒\n\n")
  (beginning-of-buffer)
  (replace-string " eggs\n" "隻 雞蛋\n")
  (beginning-of-buffer)
  (replace-string " cake bean curd (tōfu)\n" "塊 豆腐\n")
  (beginning-of-buffer)
  (replace-string " cakes tōfu (bean curd)\n" "塊 豆腐\n")
  (beginning-of-buffer)
  (replace-string " cake tōfu (bean curd)\n" "塊 豆腐\n")
  
  (beginning-of-buffer)
  (replace-string " RED MAPLE RADISH (this page)\n" " 紅楓辣椒大根泥\n")
  (beginning-of-buffer)
  (replace-string " dashi or light chicken stock\n" " 出汁或清雞湯\n")
  (beginning-of-buffer)
  (replace-string " stalks trefoil (or equivalent amount of young spinach or watercress)\n" "棵 鴨兒芹（或等量嫩菠菜或西洋菜）\n")
  (beginning-of-buffer)
  (replace-string " stalks trefoil\n" "棵 鴨兒芹\n")

  (beginning-of-buffer)
  (replace-string "finely chopped green onions" "細切（青）蔥花")
(beginning-of-buffer)
  (replace-string "finely chopped green onion" "細切（青）蔥花")

  
  (beginning-of-buffer)
  (replace-string "\nsauce:\n\n" "\n醬汁：\n\n")
  (beginning-of-buffer)
  (replace-string "\nsauces:\n\n" "\n醬汁：\n\n")

  (beginning-of-buffer)
  (replace-string "\ndipping sauce:\n\n" "\n蘸醬：\n\n")

  (beginning-of-buffer)
  (replace-string "4 CHRYSANTHEMUM TURNIPS（見此頁）\n" "4朵 菊花蕪菁（見此頁）\n")
  (beginning-of-buffer)
  (replace-string "CHRYSANTHEMUM TURNIPS" "菊花蕪菁")
  (beginning-of-buffer)
  (replace-string "finely grated giant radish (daikon-oroshi)" "現磨大根泥")
  
  (beginning-of-buffer)
  (replace-string " fresh shiitake mushrooms, wiped, trimmed, and quartered" " 鮮香菇（擦淨，去根，一切為四）\n")
  (beginning-of-buffer)
  (replace-string " shiitake mushroom, wiped, trimmed, and halved\n" "隻 香菇（擦淨，去根，對半切開）\n")
  (beginning-of-buffer)
  (replace-string " large dried shiitake mushrooms, softened and trimmed (see this page)\n" "隻 大乾香菇（泡發，去根）\n")
  (beginning-of-buffer)
  (replace-string " shiitake mushrooms or white mushrooms, wiped and trimmed\n" "隻 香菇或白蘑菇（擦淨，去根）\n")
  (beginning-of-buffer)
  (replace-string " fresh shiitake mushrooms wiped, trimmed, and sliced\n" "隻 鮮香菇（擦淨，去根，切片）\n")
  (beginning-of-buffer)
  (replace-string " fresh shiitake mushrooms, wiped and trimmed (any type of mushroom is fine)\n" "隻 鮮香菇（擦淨，去根，或其它任何蘑菇）\n")
  (beginning-of-buffer)
  (replace-string " fresh shiitake mushrooms, wiped, trimmed, and finely chopped\n" "隻 鮮香菇（擦淨，去根，切碎）\n")
  (beginning-of-buffer)
  (replace-string " shiitake mushrooms, wiped and trimmed\n" "隻 香菇（擦淨，去根）\n")
  (beginning-of-buffer)
  (replace-string " dried shiitake mushrooms, softened and trimmed（見此頁）\n" "隻 乾香菇（泡發，去根）（見此頁）\n")
  (beginning-of-buffer)
  (replace-string " dried shiitake mushrooms, softened（見此頁）\n" "隻 乾香菇（泡發）（見此頁）\n")
  (beginning-of-buffer)
  (replace-string " fresh or dried shiitake mushrooms\n" "隻 乾或新鮮香菇\n")
  (beginning-of-buffer)
  (replace-string " fresh shiitake mushrooms (or large Western-type mushrooms)\n" "隻 鮮香菇（或西式大蘑菇）\n")
  (beginning-of-buffer)
  (replace-string " fresh shiitake mushrooms wiped, trimmed, and sliced\n" "隻 鮮香菇（擦淨，去根，切片）\n")
  (beginning-of-buffer)
  (replace-string " dried shiitake mushrooms\n" "隻 乾香菇\n")
  (beginning-of-buffer)
  (replace-string "fresh shiitake mushrooms" "鮮香菇")
  (beginning-of-buffer)
  (replace-string "dried shiitake mushrooms" "乾香菇")
  (beginning-of-buffer)
  (replace-string "shiitake mushrooms" "香菇")
  (beginning-of-buffer)
  (replace-string "shiitake" "香菇")
  (beginning-of-buffer)
  (replace-string " large fresh mushrooms (any kind), wiped and trimmed\n" " 鮮蘑菇（大，任何品種，擦淨，去根）\n")
    (beginning-of-buffer)
  (replace-string " bunch enokitake mushrooms, trimmed and washed\n" "捆 金針菇（洗淨，去根）\n")
    (beginning-of-buffer)
  (replace-string " bunches enokitake mushrooms, washed and trimmed\n" "捆 金針菇（洗淨，去根）\n")
    (beginning-of-buffer)
  (replace-string " bunch enokitake mushrooms, trimmed\n" "捆 金針菇（去根）\n")
    (beginning-of-buffer)
  (replace-string " bunches enokitake mushrooms\n" "捆 金針菇\n")
    (beginning-of-buffer)
  (replace-string "enokitake mushrooms" "金針菇")
  (beginning-of-buffer)
  (replace-string "enokitake" "金針菇")
  
  (beginning-of-buffer)
  (replace-string "450克 red shiso leaves (green shiso will not substitute)" "450克 紅紫蘇葉（綠紫蘇不能代替）")
  (beginning-of-buffer)
  (replace-string "4–8 shiso leaves" "4-8片 紫蘇葉")
  (beginning-of-buffer)
  (replace-string "4 shiso leaves, finely cut" "4片 紫蘇葉（切碎）")
  (beginning-of-buffer)
  (replace-string "4 shiso leaves" "4片 紫蘇葉")
  (beginning-of-buffer)
  (replace-string "finely chopped shiso leaf" "切碎紫蘇葉")
  (beginning-of-buffer)
  (replace-string "red shiso leaves" "紅紫蘇葉")
  (beginning-of-buffer)
  (replace-string "green shiso leaves" "綠紫蘇葉")
  


  
  (beginning-of-buffer)
  (replace-string " standard sheets nori seaweed\n" "張 海苔（標準大小）\n")
  (beginning-of-buffer)
  (replace-string " sushi rice\n" " 壽司飯\n")
  (beginning-of-buffer)
  (replace-string " finely grated wasabi horseradish\n" " 現磨山葵\n")
  
  (beginning-of-buffer)
  (replace-string "\nmarinade:\n\n" "\n醃料：\n\n")
  (beginning-of-buffer)
  (replace-string " finely shred-cut, toasted nori seaweed\n" " 青海苔\n")
  (beginning-of-buffer)
  (replace-string " grated wasabi horseradish" " 現磨山葵\n")
  (beginning-of-buffer)

  (beginning-of-buffer)
  (replace-string "shōchū" "燒酒")
  (beginning-of-buffer)
  (replace-string " water, boiled and cooled\n" " 冷開水\n")
  (beginning-of-buffer)
  (replace-string " powdered mustard\n" " 芥末粉\n")
  (beginning-of-buffer)
  (replace-string " dashi (or light chicken stock)\n" " 出汁（或清雞湯）\n")

  (beginning-of-buffer)
  (replace-string " small carrots\n" "隻 胡蘿蔔（小）\n")

  
  (beginning-of-buffer)

    (beginning-of-buffer)




    (beginning-of-buffer)

  (beginning-of-buffer)
  (replace-string " new potatoes, peeled and sliced\n" "隻 新洋山芋（去皮，切片）\n")
  (beginning-of-buffer)
  (replace-string " dashi (or light chicken or beef stock)\n" " 出汁（或清雞湯，或牛肉高湯）\n")
  (beginning-of-buffer)
  (replace-string " medium carrot\n" " 胡蘿蔔（中）\n")
  (beginning-of-buffer)
  (replace-string "TOSA SOY SAUCE" "土佐醬油")
  (beginning-of-buffer)
  (replace-string "RED MAPLE RADISH" "紅楓辣椒大根泥")

  (beginning-of-buffer)
  (replace-string "其他" "其它")


  (beginning-of-buffer)
  (replace-string " (see this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string " (see this page)" "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(see this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(see this page)" "（見此頁）")
  (beginning-of-buffer)
  (replace-string " (this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string " (this page)" "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(this page) " "（見此頁）")
  (beginning-of-buffer)
  (replace-string "(this page)" "（見此頁）")
  


  (beginning-of-buffer)
  (replace-string "1/16-inch (¼-cm)" "¼厘米")
  (beginning-of-buffer)
  (replace-string "1/16 inch (¼ cm)" "¼厘米")
  (beginning-of-buffer)
  (replace-string "1/16 inch" "¼厘米")
  (beginning-of-buffer)
  (replace-string "⅛-inch (½-cm)" "½厘米")
  (beginning-of-buffer)
  (replace-string "⅛-inch [½-cm]" "½厘米")
  (beginning-of-buffer)
  (replace-string "⅛ inch (½ cm)" "½厘米")
  (beginning-of-buffer)
  (replace-string "¼-inch (¾-cm)" "¾厘米")
  (beginning-of-buffer)
  (replace-string "¼ inch [¾ cm]" "¾厘米")
  (beginning-of-buffer)
  (replace-string "¼ inch (¾ cm)" "¾厘米")  
  (beginning-of-buffer)
  (replace-string "¼-inch (1¼-cm)" "1¼厘米")
  (beginning-of-buffer)
  (replace-string "⅓-inch (⅘-cm)" "⅘厘米")
  (beginning-of-buffer)
  (replace-string "⅜-inch (1-cm)" "1厘米")
  (beginning-of-buffer)
  (replace-string "⅜ inch (1-cm)" "1厘米")
  (beginning-of-buffer)
  (replace-string "⅜ inch (1 cm)" "1厘米")
  (beginning-of-buffer)
  (replace-string "½-inch (1½-cm)" "1½厘米")
  (beginning-of-buffer)
  (replace-string "½ inch (1½ cm)" "1½厘米")
  (beginning-of-buffer)
  (replace-string "¾-inch (2-cm)" "2厘米")
  (beginning-of-buffer)
 (replace-string "¾ inch (2 cm)" "2厘米")
  (beginning-of-buffer)
  (replace-string "1-inch (2½-cm)" "2½厘米")
  (beginning-of-buffer)
  (replace-string "1 inch (2½-cm)" "2½厘米")
  (beginning-of-buffer)
  (replace-string "1 inch (2½ cm)" "2½厘米")
  (beginning-of-buffer)
  (replace-string "1-inch [2½-cm]" "2½厘米")
  (beginning-of-buffer)
  (replace-string "1¼-inch (3½-cm)" "3½厘米")
  (beginning-of-buffer)
  (replace-string "1½-inch (4-cm)" "4厘米")
  (beginning-of-buffer)
  (replace-string "1½ inch (4-cm)" "4厘米")
  (beginning-of-buffer)
  (replace-string "1 ½ inches (4 cm)" "4厘米")
  (beginning-of-buffer)
  (replace-string "1¾-inch (4½-cm)" "4½厘米")
  (beginning-of-buffer)
  (replace-string "2-inch (5-cm)" "5厘米")
  (beginning-of-buffer)
  (replace-string "2 inches (5 cm)" "5厘米")
  (beginning-of-buffer)
  (replace-string "2-inch [5-cm]" "5厘米")

  (beginning-of-buffer)
  (replace-string "2½-inch (6½-cm)" "6½厘米")
  (beginning-of-buffer)
  (replace-string "2½ inches (6½ cm)" "6½厘米")
  (beginning-of-buffer)
  (replace-string "2½ inches" "6½厘米")
  (beginning-of-buffer)
  (replace-string "2½-inch (4-cm)" "4厘米")
  
  (beginning-of-buffer)
  (replace-string "3 inches (6½ cm)" "8厘米")
  (beginning-of-buffer)
  (replace-string "3-inch (8-cm)" "8厘米")
  (beginning-of-buffer)
  (replace-string "3 inches (8 cm)" "8厘米")
  (beginning-of-buffer)
  (replace-string "3 inch (8 cm)" "8厘米")
  (beginning-of-buffer)
  (replace-string "3½-inch (9-cm)" "9厘米")
  (beginning-of-buffer)
  (replace-string "4-inch (10-cm)" "10厘米")
 (beginning-of-buffer)
  (replace-string "4-inch (10 cm)" "10厘米")
  (beginning-of-buffer)
  (replace-string "4 inches (10 cm)" "10厘米")
  (beginning-of-buffer)
  (replace-string "4½ inches (11½ cm)" "11½厘米")
  (beginning-of-buffer)
  (replace-string "5-inches (13-cm)" "13厘米")
  (beginning-of-buffer)
  (replace-string "5 inches (13 cm)" "13厘米")
  (beginning-of-buffer)
  (replace-string "5-inch (13 cm)" "13厘米")
  (beginning-of-buffer)
  (replace-string "5-inch (13-cm)" "13厘米")

  (beginning-of-buffer)
  (replace-string "5½ inches (14 cm)" "14厘米")
  (beginning-of-buffer)
  (replace-string "6 inches (15-cm)" "15厘米")
  (beginning-of-buffer)
  (replace-string "6 inches (15 cm)" "15厘米")
  (beginning-of-buffer)
  (replace-string "6-inch (15-cm)" "15厘米")
  (beginning-of-buffer)
  (replace-string "6-inch [15-cm]" "15厘米")
  (beginning-of-buffer)
  (replace-string "7-inch (18-cm)" "18厘米")
  (beginning-of-buffer)
  (replace-string "7-inch" "18厘米")
  (beginning-of-buffer)
  (replace-string "8-inch (20-cm)" "20厘米")
  (beginning-of-buffer)
  (replace-string "8 inches (20 cm)" "20厘米")
  (beginning-of-buffer)
  (replace-string "9 inches (23 cm)" "23厘米")
  (beginning-of-buffer)
  (replace-string "9-inch (23-cm)" "23厘米")
  (beginning-of-buffer)
  (replace-string "10-inch (25-cm)" "25厘米")
  (beginning-of-buffer)
  (replace-string "10 inches (25 cm)" "25厘米")
  (beginning-of-buffer)
  (replace-string "10 inch (25 cm)" "25厘米")
  (beginning-of-buffer)
  (replace-string "Ten-inch (25-cm)" "25厘米")
  (beginning-of-buffer)
  (replace-string "12-inch (30-cm)" "30厘米")
  (beginning-of-buffer)
  (replace-string "12-inch" "30厘米")
  (beginning-of-buffer)
  (replace-string "14-inch (35-cm)" "35厘米")
  (beginning-of-buffer)
  (replace-string "14 inches (35 cm)" "35厘米")
  (beginning-of-buffer)
  (replace-string "14 inches" "35厘米")
  (beginning-of-buffer)
  (replace-string "15-inch (35-cm)" "35厘米")
    (beginning-of-buffer)
  (replace-string "18-inch (45-cm)" "45厘米")
    (beginning-of-buffer)
  (replace-string "20 inches (50 cm)" "50厘米")
  (beginning-of-buffer)
  (replace-string "⅛ to ¼ inch (½ to ¾ cm)" "½-¾厘米")
  (beginning-of-buffer)
  (replace-string "⅛–¼ inch (½–¾ cm)" "½-¾厘米")
  (beginning-of-buffer)
  (replace-string "⅛ to ⅜ inch (½ to 1 cm)" "½-1厘米")
  (beginning-of-buffer)
  (replace-string "¼ to ½ inch (¾ to 1½ cm)" "¾-1½厘米")
  (beginning-of-buffer)
  (replace-string "¾ to 1 inch (2 to 2½ cm)" "2-2½厘米")
  (beginning-of-buffer)
  (replace-string "1 to 1½ inches (2½ to 4 cm)" "2½-4厘米")
  (beginning-of-buffer)
  (replace-string "1 to 1½ inches (2½ to 4 cm)" "2½-4厘米")
  (beginning-of-buffer)
  (replace-string "1½- to 2-inch (4- to 5-cm)" "4-5厘米")
  (beginning-of-buffer)
  (replace-string "1½–2-inch (4–5-cm)" "4-5厘米")
  (beginning-of-buffer)
  (replace-string "2 to 3 inches (5 to 8 cm)" "5-8厘米")
  (beginning-of-buffer)
  (replace-string "2½ to 12 inches (6 to 30 cm)" "6-30厘米")
  (beginning-of-buffer)
  (replace-string "3- or 4-inch (8- or 10-cm)" "8-10厘米")
  (beginning-of-buffer)
  (replace-string "3-4 inches (8-10 cm)" "8-10厘米")
  (beginning-of-buffer)
  (replace-string "3 to 4 inches (8 to 10 cm)" "8-10厘米")
  (beginning-of-buffer)
  (replace-string "3 to 5 inches (8 to 13 cm)" "8-13厘米")
  (beginning-of-buffer)
  (replace-string "4–5 inches (10–13 cm)" "10-13厘米")
  (beginning-of-buffer)
  (replace-string "4 to 5 inches (10 to 13 cm)" "10-13厘米")
  (beginning-of-buffer)
  (replace-string "4 or 5 inches (10 or 13 cm)" "10-13厘米")
  (beginning-of-buffer)
  (replace-string "5 to 6 inches (13 to 15 cm)" "13-15厘米")
  (beginning-of-buffer)
    (replace-string "5 to 8 inches (13 to 20 cm)" "13-20厘米")
  (beginning-of-buffer)
    (replace-string "5½ to 9 inches (14 to 23 cm)" "14-23厘米")
  (beginning-of-buffer)
  (replace-string "6 to 7 inches (15 to 18 cm)" "15-18厘米")
  (beginning-of-buffer)
  (replace-string "6-8-inch (15-20-cm)" "15-20厘米")
  (beginning-of-buffer)
  (replace-string "6 to 8 inches (15 to 20 cm)" "15-20厘米")
  (beginning-of-buffer)
  (replace-string "6- to 8-inch (15- to 20-cm)" "15-20厘米")
  (beginning-of-buffer)
  (replace-string "7- or 8-inch (18- or 20-cm)" "18-20厘米")
  (beginning-of-buffer)
  (replace-string "7 to 12 inches (18 to 30 cm)" "18-30厘米")
  (beginning-of-buffer)
  (replace-string "7 to 15 inches (18 to 39 cm)" "18-39厘米")
  (beginning-of-buffer)
  (replace-string "8 to 9 inches (20 to 23 cm)" "20-23厘米")
  (beginning-of-buffer)
  (replace-string "8 or 9 inches (20 or 23 cm)" "20-23厘米")
  (beginning-of-buffer)
  (replace-string "8 to 10 inches (20 to 25 cm)" "20-25厘米")
  (beginning-of-buffer)
  (replace-string "10- to 12-inch (20- to 25-cm)" "25-30厘米")
  (beginning-of-buffer)
  (replace-string "14 to 16 inches (35 to 40 cm)" "35-40厘米")
  (beginning-of-buffer)
  (replace-string "18 to 24 inches (45–60 cm)" "45-60厘米")
  (beginning-of-buffer)
  (replace-string "¼-x-2-inch [¾-x-5-cm]" "¾×5厘米")
  (beginning-of-buffer)
  (replace-string "⅜ 1¼ inches (1 × 3 cm)" "1×3厘米")
  (beginning-of-buffer)
  (replace-string "½- × -2-inch (1½- × -5-cm)" "1½×5厘米")
  (beginning-of-buffer)
  (replace-string "½ × ¼ inch (1½ × ¾ cm)" "1½×¾厘米")
  (beginning-of-buffer)
  (replace-string "1- × -½-inch (2½- × -1½-cm)" "2½×1½厘米")
  (beginning-of-buffer)
  (replace-string "1-x-½-inch (2½-x-1½-cm)" "2½×1½厘米")
  (beginning-of-buffer)
  (replace-string "1- × -2-inch (2½- × -5-cm)" "2½×5厘米")
  (beginning-of-buffer)
  (replace-string "1 × 2½ inches (2½ × 6½ cm)" "2½×6½厘米")
  (beginning-of-buffer)
  (replace-string "1½-x-¼-inch (4-x-¾-cm)" "4×¾厘米")
  (beginning-of-buffer)
  (replace-string "1½ × ¼ inches [4 × ¾ cm]" "4×¾厘米")
  (beginning-of-buffer)
  (replace-string "1½ × -¼-inch (4- × -¾-cm)" "4×¾厘米")
  (beginning-of-buffer)
  (replace-string "1½ × ½ inches (4 × 1 cm)" "4×1厘米")
  (beginning-of-buffer)
  (replace-string "1½ × ½ inches (4 × 1½ cm)" "4×1½厘米")
  (beginning-of-buffer)
  (replace-string "1½ × ¾ inches (4 × 2 cm)" "4×2厘米")
  (beginning-of-buffer)
  (replace-string "1½ × 3 inch [3 × 7 cm]" "3×7厘米")
  

  (beginning-of-buffer)
  (replace-string "2 × 1½ inches [5 × 4 cm]" "5×4厘米")
   (beginning-of-buffer)
  (replace-string "2- × -1½-inch (5- × -1½-cm)" "5×4厘米")
  (beginning-of-buffer)
  (replace-string "2½- × -1-inch (6½- × -2½-cm)" "6½×2½厘米")
  (beginning-of-buffer)
  (replace-string "3-×-1½-inch (8- × -4-cm)" "8×4厘米")
  (beginning-of-buffer)
  (replace-string "3 by 6 inches (8 × 15 cm)" "8×15厘米")
  (beginning-of-buffer)
  (replace-string "4-x-6-inch (10-x-15-cm)" "10×15厘米")
   (beginning-of-buffer)
  (replace-string "6 x 2 inches (15 x 5 cm)" "15×5厘米")
  (beginning-of-buffer)
  (replace-string "6- × -2-inch (15- × -5-cm)" "15×5厘米")
  (beginning-of-buffer)
  (replace-string "6½-x-8-inch (17½-x-20½-cm)" "17½×20½厘米")
  (beginning-of-buffer)
  (replace-string "8 × 3 inches (20 × 8 cm)" "20×8厘米")
  (beginning-of-buffer)
  (replace-string "8 × 6⅞ inches (20½ × 17½ cm)" "20½×17½厘米")
  (beginning-of-buffer)
  (replace-string " ⅛- × -⅛- × -1½-inch (½- × -½- × -4-cm)" "½×½×4厘米")
  (beginning-of-buffer)
  (replace-string "⅜-×-¾-×-2-inch (1-×-2-×-5-cm)" "1×2×5厘米")
  (beginning-of-buffer)
  (replace-string "1½ × ½ × ⅛ inches (4 × 1½ × ½ cm)" "(4×1½×½厘米")
  (beginning-of-buffer)
  (replace-string "2¼ × 1½ × ⅜ inches (6 × 4 × 1 cm)" "(6×4×1厘米")

    (beginning-of-buffer)
  (replace-string "3½×7×1 inch (9×18×2½ cm)" "9×18×2½厘米")
  (beginning-of-buffer)
  (replace-string "6 x 2 x 1½ inches (15 x 5 x 4 cm)" "15×5×4厘米")
  (beginning-of-buffer)
  (replace-string "6 × 3¼ × ⅜ inches (15 × 8 × 1 cm)" "15×8×1厘米")
  (beginning-of-buffer)
  (replace-string "6×3×1½ inches (15×8×4 cm)" "15×8×4厘米")
  (beginning-of-buffer)
  (replace-string "1-inch" "2½厘米")
  (beginning-of-buffer)
  (replace-string "1 inch" "2½厘米")
  (beginning-of-buffer)
  (replace-string "2 inches" "5厘米")
  (beginning-of-buffer)
  (replace-string "2-inch" "5厘米")

  (beginning-of-buffer)
  (replace-string "1 foot (30 cm)" "30厘米")
  (beginning-of-buffer)
  (replace-string "a foot (30 cm)" "30厘米")


 (beginning-of-buffer)
  (replace-string "6- to 12-foot (2-4-meter)" "2-4米")

  
  
  (beginning-of-buffer)
  (replace-string "⅛ ounce (4 g)" "4克")
  (beginning-of-buffer)
  (replace-string "⅓ ounce (10 g; 1 small handful)" "10克（一小把）")
  (beginning-of-buffer)
  (replace-string "⅓ ounce (10 g" "10克")
  
  (beginning-of-buffer)
  (replace-string "⅓ ounce (8–10 g)" "8-10克")
  (beginning-of-buffer)
  (replace-string "½ ounce (15 g)" "15克")
  (beginning-of-buffer)
  (replace-string "1-ounce (30-g)" "30克")
  (beginning-of-buffer)
  (replace-string "1 ounce (30 g)" "30克")
  (beginning-of-buffer)
  (replace-string "1⅓ ounces (40 g)" "40克")
  (beginning-of-buffer)
  (replace-string "1½ ounces (40–50 g; ⅓ cup)" "40-50克")
  (beginning-of-buffer)
  (replace-string "2 ounces (60 g)" "60克")
  (beginning-of-buffer)
  (replace-string "2 ounces" "60克")
  (beginning-of-buffer)
  (replace-string "2½ ounces (70 g)" "70克")
  (beginning-of-buffer)
  (replace-string "3 ounces (85 g)" "85克")
  (beginning-of-buffer)
  (replace-string "3½-ounce (100-g) serving" "100克份")
  (beginning-of-buffer)
  (replace-string "4 ounces (115 g)" "115克")
  (beginning-of-buffer)
  (replace-string "4½-ounce [130-g]" "130克")
  (beginning-of-buffer)
  (replace-string "5-ounce (150 g)" "150克")
  (beginning-of-buffer)
  (replace-string "5 ounces (150 g)" "150克")
  (beginning-of-buffer)
  (replace-string "5½ ounces (160 g)" "160克")
  (beginning-of-buffer)
  (replace-string "6-ounce (180-g)" "180克")
  (beginning-of-buffer)
  (replace-string "6-ounce (180 g)" "180克")
  (beginning-of-buffer)
  (replace-string "6 ounces (180 g)" "180克")
  (beginning-of-buffer)
  (replace-string "6 ounces (170-180 g)" "170-180克")
  
  (beginning-of-buffer)
  (replace-string "7-ounce (200 g)" "200克")
  (beginning-of-buffer)
  (replace-string "7 ounces (200 g)" "200克")
  (beginning-of-buffer)
  (replace-string "8-ounces (225-g)" "225克")
  (beginning-of-buffer)
  (replace-string "8-ounce (225-g)" "225克")
  (beginning-of-buffer)
  (replace-string "8 ounces (225 g)" "225克")
  (beginning-of-buffer)
  (replace-string "9 ounces (250 g)" "250克")
  (beginning-of-buffer)
  (replace-string "10-ounce (285-g)" "285克")
  (beginning-of-buffer)
  (replace-string "10 ounces (285-g)" "285克")
  (beginning-of-buffer)
  (replace-string "10 ounces (300 g)" "285克")
  (beginning-of-buffer)
  (replace-string "12-ounce (340-g)" "340克")
  (beginning-of-buffer)
  (replace-string "12-ounces (340 g)" "340克")
  (beginning-of-buffer)
  (replace-string "12 ounces (340 g)" "340克")
  (beginning-of-buffer)
  (replace-string "14 ounces (400 mL)" "400毫升")
  (beginning-of-buffer)
  (replace-string "⅙–⅓ ounce (5–10 g) (roughly 1 cup)" "5-10克（大約1杯")
  (beginning-of-buffer)
  (replace-string "⅔-to-1-ounce (20-30-g)" "20-30克")
  (beginning-of-buffer)
  (replace-string "2½-3 ounces (70–80 g)" "70-80克")
  (beginning-of-buffer)
  (replace-string "4–6 ounces (115–180 g)" "115-180克")
  (beginning-of-buffer)
  (replace-string "5 to 8 ounces (140 to 225 g)" "140-225克")
  (beginning-of-buffer)
  (replace-string "6-8 ounces (180-225 g)" "180-225克")
  (beginning-of-buffer)
  (replace-string "8-10 ounces (225-285 g)" "225-285克")
  (beginning-of-buffer)
  (replace-string "8-10 ounce (225-285 g)" "225-285克")
  (beginning-of-buffer)
  (replace-string "8¾ to 10½ ounces (250 to 300 g)" "250-300克")
  (beginning-of-buffer)
  (replace-string "10- and 13-ounce (285- and 370-g)" "285-370克")
  (beginning-of-buffer)
  (replace-string "10 to 20 fluid ounces (300–600 mL)" "300-600毫升")

  (beginning-of-buffer)
  (replace-string "¼ pound or 115 grams" "115克")
  (beginning-of-buffer)
  (replace-string "¼ pound (115 g)" "115克")
  (beginning-of-buffer)
  (replace-string "½-pound (225-g)" "225克")
  (beginning-of-buffer)
  (replace-string "½ pound (225 g)" "225克")
  (beginning-of-buffer)
  (replace-string "½ pound [225 g]" "225克")
  (beginning-of-buffer)
  (replace-string "½ pound" "225克")
  (beginning-of-buffer)
  (replace-string "⅔ pound (300 g)" "300克")
  (beginning-of-buffer)
  (replace-string "⅔ pound (310 g)" "300克")
  (beginning-of-buffer)
  (replace-string "¾ pound (340 g)" "430克")
  (beginning-of-buffer)
  (replace-string "1¾ pounds (800 g)" "800克")
  (beginning-of-buffer)
  (replace-string "1-pound (450-g)" "450克")
  (beginning-of-buffer)
  (replace-string "1 pound (450-g)" "450克")
  (beginning-of-buffer)
  (replace-string "1 pound (450 g)" "450克")
  (beginning-of-buffer)
  (replace-string "about pound (450 g)" "大約450克")
  (beginning-of-buffer)
  (replace-string "1½-pounds (675 g)" "675克")
  (beginning-of-buffer)
  (replace-string "1½-pound (675 g)" "675克")
  (beginning-of-buffer)
  (replace-string "1½-pound" "675克")
  (beginning-of-buffer)
  (replace-string "1½ pounds (675 g)" "675克")
  (beginning-of-buffer)
  (replace-string "1½ pound (675 g)" "675克")
  (beginning-of-buffer)
  (replace-string "1½ pounds (650-700 g)" "675克")
  (beginning-of-buffer)
  (replace-string "1¾ pound (800 g)" "800克")
  (beginning-of-buffer)
  (replace-string "2 pounds (900 g)" "900克")
  (beginning-of-buffer)
  (replace-string "2 pounds (1 kg)" "900克")
  (beginning-of-buffer)
  (replace-string "2⅕ pounds (1 kg)" "1公斤")
  (beginning-of-buffer)
  (replace-string " (2¼ pounds or 1 kg)" "（1公斤）")
  (beginning-of-buffer)
  (replace-string "2¼-3½-pound (1-1½-kg)" "1-1½公斤")
  (beginning-of-buffer)
  (replace-string "2½ pounds (1125 g)" "1125克")
  (beginning-of-buffer)
  (replace-string "2½ pounds (1¼ kg)" "1125克")
  (beginning-of-buffer)
  (replace-string "2½ pounds (675 g)" "1125克")
  (beginning-of-buffer)
  (replace-string "3-pound (1⅓-kg)" "1⅓公斤")
  (beginning-of-buffer)
  (replace-string "4 pounds (1⅓ kg)" "1¾公斤")
  (beginning-of-buffer)
  (replace-string "4 pounds (1¾ kg)" "1¾公斤")
  (beginning-of-buffer)
  (replace-string "4 pounds (1 ¾ kg)" "1¾公斤")
  (beginning-of-buffer)
  (replace-string "4 pounds (2 kg)" "1¾公斤")
  (beginning-of-buffer)
  (replace-string "20 pounds (10 kg)" "10公斤")
  (beginning-of-buffer)
  (replace-string "1 pound of chicken" "450克雞腿")
  (beginning-of-buffer)
  (replace-string "1 pound sea salt" "450克 海鹽")
  (beginning-of-buffer)
  (replace-string "1 pound green beans, strings removed" "450克 刀豆（去筋）")

  
  )

