(add-to-list 'load-path "~/.emacs.d/site-lisp/w3m")
;; (require 'w3m-load)
;; (require 'w3m-e21)
;; (provide 'w3m-e23)
(setq w3m-use-favicon nil)
(setq w3m-command-arguments '("-cookie" "-F"))
(setq w3m-use-cookies t)
(setq w3m-home-page "http://www.yuleshow.com")
(setq w3m-display-inline-image t)
(provide 'yuleshow-w3m)
