;;; auto-save-buffers-enhanced-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auto-save-buffers-enhanced.el

(autoload 'auto-save-buffers-enhanced "auto-save-buffers-enhanced" "\
If `flag' is non-nil, activate `auto-save-buffers-enhanced' and start
auto-saving.

(fn FLAG)")
(autoload 'auto-save-buffers-enhanced-include-only-checkout-path "auto-save-buffers-enhanced" "\
If `flag' is non-nil, `auto-save-buffers-enhanced' saves only
the directories under VCS.

(fn FLAG)")
(autoload 'auto-save-buffers-enhanced-toggle-activity "auto-save-buffers-enhanced" "\
Toggle `auto-save-buffers-enhanced' activity" t)
(autoload 'auto-save-buffers-enhanced-reload-svk "auto-save-buffers-enhanced" "\
Reload the checkout paths from SVK configuration file." t)
(register-definition-prefixes "auto-save-buffers-enhanced" '("auto-save-buffers-enhanced-"))

;;; End of scraped data

(provide 'auto-save-buffers-enhanced-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auto-save-buffers-enhanced-autoloads.el ends here
