;;; org-ehtml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-ehtml-server.el

(register-definition-prefixes "org-ehtml-server" '("org-ehtml-"))


;;; Generated autoloads from org-ehtml-util.el

(register-definition-prefixes "org-ehtml-util" '("file-contents" "org-ehtml-base" "replace-region" "while-visiting-file"))


;;; Generated autoloads from ox-ehtml.el

(register-definition-prefixes "ox-ehtml" '("def-ehtml-wrap" "org-ehtml-"))

;;; End of scraped data

(provide 'org-ehtml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-ehtml-autoloads.el ends here
